#!/usr/bin/env python

import sys
from iqe import *

def strip_material_name(model):
	for mesh in model.meshes:
		m = mesh.material
		mesh.material = [m[-1]]

def rename_meshes(model):
	for mesh in model.meshes:
		name = mesh.name
		name = name.split("+")[0].split(",")[0].split(".")[0]
		print >>sys.stderr, name, mesh.material
		mesh.name = name

def rename_meshes2(model):
	for mesh in model.meshes:
		name = mesh.name
		print >>sys.stderr, name, mesh.material
		mesh.name = mesh.material[-1]

m = load_model(sys.stdin)
#strip_material_name(m)
merge_meshes(m)
rename_meshes2(m)
m.save(sys.stdout)
