#!/usr/bin/env python

import sys
from iqe import *

m = load_model(sys.stdin)

if len(sys.argv) > 1:
	matname = sys.argv[1]
	a = load_material(open(matname))
	annotate_model(m, a)

m.save(sys.stdout)
