#!/usr/bin/env python

import sys
from iqe import *

def strip_material_name(model):
	for mesh in model.meshes:
		m = mesh.material
		if 'alphatest' in m: m.remove('alphatest')
		if 'alphagloss' in m: m.remove('alphagloss')

def rename_meshes(model):
	for mesh in model.meshes:
		name = mesh.name
		name = name.split("+")[0].split(",")[0].split(".")[0]
		print >>sys.stderr, name, mesh.material
		mesh.name = name

m = load_model(sys.stdin)
strip_material_name(m)
merge_meshes(m)
rename_meshes(m)
m.save(sys.stdout)
