#!/usr/bin/env python

import sys
from iqe import *

#ryzom = [ "bip01", "bip01_pelvis", "bip01_l_clavicle", "bip01_r_clavicle", "bip01_spine", "bip01_tail" ]
ryzom = [ "bip01", "bip01_l_clavicle", "bip01_r_clavicle", "bip01_spine", "bip01_tail" ]

def kill_loc(n):
	if not n in ryzom: return True
	return False

def kill_rot(n):
	return False

def kill_scale(n):
	return True

model = load_model(sys.stdin)
kill_channels(model, kill_loc, kill_rot, kill_scale)
model.save(sys.stdout)
