#!/usr/bin/env python

import sys
from iqe import *

list = []

for line in open(sys.argv[1]).readlines():
	line = line.strip()
	list += [line]

m = load_model(sys.stdin)
select_bones(m, list)
m.save(sys.stdout)
