#!/usr/bin/env python

import sys
from iqe import *

list = [ load_model(open(a)) for a in sys.argv[1:] ]

bones = None
for model in list:
	if len(model.bones):
		bones = model

if bones:
	for model in list:
		for mesh in model.meshes:
			if len(mesh.blends) == 0:
				mesh.blends = [ ( (0, 1), ) ] * len(mesh.positions)
	joined = bones
	for model in list:
		if model != joined:
			joined.meshes += model.meshes
else:
	joined = list[0]
	for model in list[1:]:
		joined.meshes += model.meshes

joined.save(sys.stdout)
